version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - stack
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    networks:
      - stack
    volumes:
      - redis:/data

  celery:
    image: celery-sqlalchemy-boilerplate
    command: celery -A app worker
    environment: &environment
      - CELERY_BACKEND=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres@postgres:5432/postgres
    networks:
      - stack

  celery-beat:
    image: celery-sqlalchemy-boilerplate
    command: celery -A app beat
    environment: *environment
    networks:
      - stack

  flower:
    image: celery-sqlalchemy-boilerplate
    command: celery -A app flower
    environment: *environment
    ports:
      - 8000:5555
    networks:
      - stack
      - ingress

networks:
  stack:
    internal: true
  ingress:

volumes:
  postgres:
  redis:
